### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by Sergey-Ryabov** [Everpoint/everGis#28]
Hi! Is there any tutorial with usage examples? Can i use it with Angular?

**Comment by Maximkaaa** [comment]
Hi @Sergey-Ryabov . The developement of this project was dropped in favour of another version, which is currently developed in a private git repository. I will archive this repo to prevent future questions.

If you are interested in everGis system, check out our public application at evergis.ru, or contact us on facebook or mail (see everpoint.ru).
